const firstSentence = (text) => (text || 'Empty note.').split(/[.!?]/).find(Boolean)?.trim() || 'Empty note';

export function createMockAiProvider() {
  return {
    async summary(text) { return `Summary: ${firstSentence(text)}.`; },
    async keyPoints(text) { return [`Main topic: ${firstSentence(text)}`, 'Review the full transcript for details', 'Generated by the free mock provider']; },
    async actionItems(text) { return [{ text: text?.toLowerCase().includes('follow up') ? 'Follow up with the mentioned person' : 'Review this note', dueDate: null, completed: false }]; },
    async mindMap(text) { return { root: 'Note', children: [{ label: firstSentence(text), children: [{ label: 'Summary' }, { label: 'Action items' }] }] }; }
  };
}

export function createAiProvider(name = process.env.AI_PROVIDER || 'mock') {
  if (name !== 'mock') {
    console.warn(`AI_PROVIDER=${name} not implemented yet; falling back to mock. Add Ollama/local OpenAI-compatible provider here.`);
  }
  return createMockAiProvider();
}
